"""tracking and ml schemas

Revision ID: 0001
Revises: 
Create Date: 2026-09-11 04:18:41.624241
"""
from __future__ import annotations

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


APPEND_ONLY_FN = """
CREATE OR REPLACE FUNCTION {schema}.forbid_modification() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION '% on %.% is not allowed: rows are permanent (append-only)', TG_OP, TG_TABLE_SCHEMA, TG_TABLE_NAME;
END $$;
"""

MODEL_IDENTITY_FN = """
CREATE OR REPLACE FUNCTION ml.protect_model_identity() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.version IS DISTINCT FROM OLD.version
       OR NEW.version_number IS DISTINCT FROM OLD.version_number
       OR NEW.parent_version IS DISTINCT FROM OLD.parent_version
       OR NEW.architecture_version IS DISTINCT FROM OLD.architecture_version
       OR NEW.model_path IS DISTINCT FROM OLD.model_path
       OR NEW.scaler_path IS DISTINCT FROM OLD.scaler_path
       OR NEW.artifact_sha256 IS DISTINCT FROM OLD.artifact_sha256
       OR NEW.training_data_cutoff IS DISTINCT FROM OLD.training_data_cutoff THEN
        RAISE EXCEPTION 'model version % is immutable (only status fields may change)', OLD.version;
    END IF;
    RETURN NEW;
END $$;
"""

TRIGGERS = [
    ("ml", "forecasts", "UPDATE OR DELETE", "forbid_modification"),
    ("ml", "forecast_sets", "UPDATE OR DELETE", "forbid_modification"),
    ("ml", "forecast_evaluations", "UPDATE OR DELETE", "forbid_modification"),
    ("ml", "model_status_events", "UPDATE OR DELETE", "forbid_modification"),
    ("ml", "model_versions", "DELETE", "forbid_modification"),
    ("ml", "model_versions", "UPDATE", "protect_model_identity"),
    ("tracking", "observations", "DELETE", "forbid_modification"),
    ("tracking", "observation_revisions", "UPDATE OR DELETE", "forbid_modification"),
]


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE SCHEMA IF NOT EXISTS tracking")
    op.execute("CREATE SCHEMA IF NOT EXISTS ml")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retraining_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('eligibility', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('champion_version', sa.String(length=32), nullable=True),
    sa.Column('candidate_version', sa.String(length=32), nullable=True),
    sa.Column('source_data_cutoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('dataset_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'skipped', 'promoted', 'rejected', 'failed')", name=op.f('ck_retraining_runs_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retraining_runs')),
    sa.UniqueConstraint('run_id', name=op.f('uq_retraining_runs_run_id')),
    schema='ml'
    )
    op.create_index(op.f('ix_ml_retraining_runs_status'), 'retraining_runs', ['status'], unique=False, schema='ml')
    op.create_table('ingestion_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('discovery_method', sa.String(length=32), nullable=True),
    sa.Column('trigger', sa.String(length=32), server_default='scheduled', nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('raw_file_path', sa.Text(), nullable=True),
    sa.Column('header', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('row_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('valid_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('new_observations', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_observations', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duplicate_observations', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('missing_from_source', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source_latest_update', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'success', 'partial', 'unchanged', 'failed')", name=op.f('ck_ingestion_runs_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs')),
    schema='tracking'
    )
    op.create_index('ix_ingestion_runs_source_fetched_at', 'ingestion_runs', ['source', 'fetched_at'], unique=False, schema='tracking')
    op.create_index(op.f('ix_tracking_ingestion_runs_checksum_sha256'), 'ingestion_runs', ['checksum_sha256'], unique=False, schema='tracking')
    op.create_table('model_versions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('parent_version', sa.String(length=32), nullable=True),
    sa.Column('architecture', sa.String(length=32), nullable=False),
    sa.Column('architecture_version', sa.String(length=64), nullable=False),
    sa.Column('input_sequence_length', sa.Integer(), nullable=False),
    sa.Column('input_semantics', sa.String(length=64), nullable=False),
    sa.Column('forecast_horizon_days', sa.Integer(), nullable=False),
    sa.Column('feature_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('adapter_strategy', sa.String(length=32), nullable=True),
    sa.Column('model_path', sa.Text(), nullable=False),
    sa.Column('scaler_path', sa.Text(), nullable=False),
    sa.Column('metadata_path', sa.Text(), nullable=False),
    sa.Column('artifact_sha256', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifact_origin', sa.String(length=64), nullable=False),
    sa.Column('training_data_cutoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_sample_count', sa.Integer(), nullable=True),
    sa.Column('training_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dataset_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('test_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('day1_error', sa.Float(), nullable=True),
    sa.Column('day3_error', sa.Float(), nullable=True),
    sa.Column('day7_error', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('retraining_run_id', sa.BigInteger(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('candidate', 'validated', 'deployed', 'rejected', 'archived')", name=op.f('ck_model_versions_status')),
    sa.CheckConstraint('version_number >= 0', name=op.f('ck_model_versions_version_number')),
    sa.ForeignKeyConstraint(['parent_version'], ['ml.model_versions.version'], name=op.f('fk_model_versions_parent_version_model_versions')),
    sa.ForeignKeyConstraint(['retraining_run_id'], ['ml.retraining_runs.id'], name=op.f('fk_model_versions_retraining_run_id_retraining_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('version', name=op.f('uq_model_versions_version')),
    sa.UniqueConstraint('version_number', name=op.f('uq_model_versions_version_number')),
    schema='ml'
    )
    op.create_index(op.f('ix_ml_model_versions_parent_version'), 'model_versions', ['parent_version'], unique=False, schema='ml')
    op.create_index(op.f('ix_ml_model_versions_status'), 'model_versions', ['status'], unique=False, schema='ml')
    op.create_index('uq_model_versions_single_deployed', 'model_versions', ['status'], unique=True, schema='ml', postgresql_where=sa.text("status = 'deployed'"))
    op.create_table('icebergs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('iceberg_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.Column('first_official_seen', sa.Date(), nullable=True),
    sa.Column('last_official_seen', sa.Date(), nullable=True),
    sa.Column('last_seen_in_source_run_id', sa.BigInteger(), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'not_in_latest_source', 'historical_only')", name=op.f('ck_icebergs_status')),
    sa.ForeignKeyConstraint(['last_seen_in_source_run_id'], ['tracking.ingestion_runs.id'], name=op.f('fk_icebergs_last_seen_in_source_run_id_ingestion_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_icebergs')),
    sa.UniqueConstraint('iceberg_id', name=op.f('uq_icebergs_iceberg_id')),
    schema='tracking'
    )
    op.create_index(op.f('ix_tracking_icebergs_status'), 'icebergs', ['status'], unique=False, schema='tracking')
    op.create_table('ingestion_row_errors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_row', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['tracking.ingestion_runs.id'], name=op.f('fk_ingestion_row_errors_ingestion_run_id_ingestion_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_row_errors')),
    schema='tracking'
    )
    op.create_index(op.f('ix_tracking_ingestion_row_errors_ingestion_run_id'), 'ingestion_row_errors', ['ingestion_run_id'], unique=False, schema='tracking')
    op.create_table('forecast_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('icebergs_considered', sa.Integer(), server_default='0', nullable=False),
    sa.Column('forecast_sets_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('already_forecast', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('running', 'success', 'partial', 'failed', 'skipped')", name=op.f('ck_forecast_runs_status')),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['tracking.ingestion_runs.id'], name=op.f('fk_forecast_runs_ingestion_run_id_ingestion_runs')),
    sa.ForeignKeyConstraint(['model_version'], ['ml.model_versions.version'], name=op.f('fk_forecast_runs_model_version_model_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_runs')),
    schema='ml'
    )
    op.create_index(op.f('ix_ml_forecast_runs_model_version'), 'forecast_runs', ['model_version'], unique=False, schema='ml')
    op.create_table('model_metrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('protocol', sa.String(length=96), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=True),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('mae_km', sa.Float(), nullable=True),
    sa.Column('rmse_km', sa.Float(), nullable=True),
    sa.Column('median_km', sa.Float(), nullable=True),
    sa.Column('p90_km', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('retraining_run_id', sa.BigInteger(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_version'], ['ml.model_versions.version'], name=op.f('fk_model_metrics_model_version_model_versions')),
    sa.ForeignKeyConstraint(['retraining_run_id'], ['ml.retraining_runs.id'], name=op.f('fk_model_metrics_retraining_run_id_retraining_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_metrics')),
    schema='ml'
    )
    op.create_index('ix_model_metrics_lookup', 'model_metrics', ['model_version', 'protocol', 'horizon_days', 'computed_at'], unique=False, schema='ml')
    op.create_table('model_status_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('retraining_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_version'], ['ml.model_versions.version'], name=op.f('fk_model_status_events_model_version_model_versions')),
    sa.ForeignKeyConstraint(['retraining_run_id'], ['ml.retraining_runs.id'], name=op.f('fk_model_status_events_retraining_run_id_retraining_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_status_events')),
    schema='ml'
    )
    op.create_index(op.f('ix_ml_model_status_events_model_version'), 'model_status_events', ['model_version'], unique=False, schema='ml')
    op.create_table('observations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('iceberg_id', sa.String(length=32), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('length_nm', sa.Float(), nullable=True),
    sa.Column('width_nm', sa.Float(), nullable=True),
    sa.Column('area_sq_nm', sa.Float(), nullable=True),
    sa.Column('area_sq_km', sa.Float(), nullable=True),
    sa.Column('area_sq_mi', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=True),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('position_sensor', sa.String(length=16), nullable=True),
    sa.Column('raw_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provenance IN ('official_usnic', 'historical_training_dataset', 'derived', 'interpolated', 'predicted')", name=op.f('ck_observations_provenance')),
    sa.CheckConstraint("provenance NOT IN ('predicted')", name=op.f('ck_observations_not_predicted')),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180', name=op.f('ck_observations_coordinates')),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_observations_revision')),
    sa.ForeignKeyConstraint(['iceberg_id'], ['tracking.icebergs.iceberg_id'], name=op.f('fk_observations_iceberg_id_icebergs'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['tracking.ingestion_runs.id'], name=op.f('fk_observations_ingestion_run_id_ingestion_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations')),
    sa.UniqueConstraint('iceberg_id', 'observation_date', 'provenance', name='uq_observations_iceberg_date_provenance'),
    schema='tracking'
    )
    op.create_index('ix_observations_geom', 'observations', ['geom'], unique=False, schema='tracking', postgresql_using='gist')
    op.create_index('ix_observations_iceberg_date_desc', 'observations', ['iceberg_id', 'observation_date'], unique=False, schema='tracking')
    op.create_index('ix_observations_official_date', 'observations', ['observation_date'], unique=False, schema='tracking', postgresql_where="provenance = 'official_usnic'")
    op.create_index(op.f('ix_tracking_observations_ingestion_run_id'), 'observations', ['ingestion_run_id'], unique=False, schema='tracking')
    op.create_index(op.f('ix_tracking_observations_provenance'), 'observations', ['provenance'], unique=False, schema='tracking')
    op.create_table('forecast_sets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('forecast_run_id', sa.BigInteger(), nullable=False),
    sa.Column('iceberg_id', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('anchor_observation_id', sa.BigInteger(), nullable=False),
    sa.Column('latest_observation_date', sa.Date(), nullable=False),
    sa.Column('adapter_version', sa.String(length=64), nullable=False),
    sa.Column('adapter_strategy', sa.String(length=32), nullable=False),
    sa.Column('input_observation_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('input_entries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diagnostics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='issued', nullable=False),
    sa.ForeignKeyConstraint(['anchor_observation_id'], ['tracking.observations.id'], name=op.f('fk_forecast_sets_anchor_observation_id_observations')),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['ml.forecast_runs.id'], name=op.f('fk_forecast_sets_forecast_run_id_forecast_runs')),
    sa.ForeignKeyConstraint(['iceberg_id'], ['tracking.icebergs.iceberg_id'], name=op.f('fk_forecast_sets_iceberg_id_icebergs')),
    sa.ForeignKeyConstraint(['model_version'], ['ml.model_versions.version'], name=op.f('fk_forecast_sets_model_version_model_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_sets')),
    sa.UniqueConstraint('iceberg_id', 'model_version', 'anchor_observation_id', name='uq_forecast_sets_iceberg_model_anchor'),
    schema='ml'
    )
    op.create_index('ix_forecast_sets_iceberg_generated', 'forecast_sets', ['iceberg_id', 'generated_at'], unique=False, schema='ml')
    op.create_index(op.f('ix_ml_forecast_sets_forecast_run_id'), 'forecast_sets', ['forecast_run_id'], unique=False, schema='ml')
    op.create_index(op.f('ix_ml_forecast_sets_model_version'), 'forecast_sets', ['model_version'], unique=False, schema='ml')
    op.create_table('observation_revisions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('previous_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('replaced_by_ingestion_run_id', sa.BigInteger(), nullable=True),
    sa.Column('replaced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['tracking.observations.id'], name=op.f('fk_observation_revisions_observation_id_observations')),
    sa.ForeignKeyConstraint(['replaced_by_ingestion_run_id'], ['tracking.ingestion_runs.id'], name=op.f('fk_observation_revisions_replaced_by_ingestion_run_id_ingestion_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observation_revisions')),
    sa.UniqueConstraint('observation_id', 'revision', name='uq_observation_revisions_obs_revision'),
    schema='tracking'
    )
    op.create_index(op.f('ix_tracking_observation_revisions_observation_id'), 'observation_revisions', ['observation_id'], unique=False, schema='tracking')
    op.create_table('forecasts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('forecast_set_id', sa.BigInteger(), nullable=False),
    sa.Column('iceberg_id', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latest_observation_date', sa.Date(), nullable=False),
    sa.Column('forecast_horizon_days', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted_latitude', sa.Float(), nullable=False),
    sa.Column('predicted_longitude', sa.Float(), nullable=False),
    sa.Column('predicted_x_m', sa.Float(), nullable=False),
    sa.Column('predicted_y_m', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('risk_radius_km_p90', sa.Float(), nullable=True),
    sa.Column('provenance', sa.String(length=16), server_default='predicted', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='issued', nullable=False),
    sa.CheckConstraint("provenance = 'predicted'", name=op.f('ck_forecasts_provenance')),
    sa.CheckConstraint('forecast_horizon_days BETWEEN 1 AND 7', name=op.f('ck_forecasts_horizon')),
    sa.ForeignKeyConstraint(['forecast_set_id'], ['ml.forecast_sets.id'], name=op.f('fk_forecasts_forecast_set_id_forecast_sets')),
    sa.ForeignKeyConstraint(['model_version'], ['ml.model_versions.version'], name=op.f('fk_forecasts_model_version_model_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecasts')),
    sa.UniqueConstraint('forecast_set_id', 'forecast_horizon_days', name='uq_forecasts_set_horizon'),
    schema='ml'
    )
    op.create_index('ix_forecasts_geom', 'forecasts', ['geom'], unique=False, schema='ml', postgresql_using='gist')
    op.create_index('ix_forecasts_iceberg_forecast_date', 'forecasts', ['iceberg_id', 'forecast_date'], unique=False, schema='ml')
    op.create_index('ix_forecasts_model_horizon', 'forecasts', ['model_version', 'forecast_horizon_days'], unique=False, schema='ml')
    op.create_index(op.f('ix_ml_forecasts_forecast_date'), 'forecasts', ['forecast_date'], unique=False, schema='ml')
    op.create_index(op.f('ix_ml_forecasts_generated_at'), 'forecasts', ['generated_at'], unique=False, schema='ml')
    op.create_table('forecast_evaluations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('forecast_id', sa.BigInteger(), nullable=False),
    sa.Column('iceberg_id', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('forecast_horizon_days', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted_latitude', sa.Float(), nullable=False),
    sa.Column('predicted_longitude', sa.Float(), nullable=False),
    sa.Column('actual_latitude', sa.Float(), nullable=False),
    sa.Column('actual_longitude', sa.Float(), nullable=False),
    sa.Column('error_km', sa.Float(), nullable=False),
    sa.Column('actual_observation_id', sa.BigInteger(), nullable=False),
    sa.Column('actual_observation_revision', sa.Integer(), nullable=False),
    sa.Column('actual_source', sa.String(length=32), nullable=False),
    sa.Column('actual_observation_date', sa.Date(), nullable=False),
    sa.Column('evaluation_mode', sa.String(length=16), server_default='operational', nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("evaluation_mode = 'research' OR actual_source = 'official_usnic'", name=op.f('ck_forecast_evaluations_official_ground_truth')),
    sa.ForeignKeyConstraint(['actual_observation_id'], ['tracking.observations.id'], name=op.f('fk_forecast_evaluations_actual_observation_id_observations')),
    sa.ForeignKeyConstraint(['forecast_id'], ['ml.forecasts.id'], name=op.f('fk_forecast_evaluations_forecast_id_forecasts')),
    sa.ForeignKeyConstraint(['model_version'], ['ml.model_versions.version'], name=op.f('fk_forecast_evaluations_model_version_model_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_evaluations')),
    sa.UniqueConstraint('forecast_id', 'actual_observation_id', 'actual_observation_revision', name='uq_forecast_evaluations_forecast_actual'),
    schema='ml'
    )
    op.create_index('ix_forecast_evaluations_iceberg', 'forecast_evaluations', ['iceberg_id', 'forecast_date'], unique=False, schema='ml')
    op.create_index('ix_forecast_evaluations_model_horizon', 'forecast_evaluations', ['model_version', 'forecast_horizon_days'], unique=False, schema='ml')
    op.create_index(op.f('ix_ml_forecast_evaluations_evaluated_at'), 'forecast_evaluations', ['evaluated_at'], unique=False, schema='ml')
    op.create_index(op.f('ix_ml_forecast_evaluations_forecast_id'), 'forecast_evaluations', ['forecast_id'], unique=False, schema='ml')
    # ### end Alembic commands ###

    # Database-enforced permanence of observations, forecasts, evaluations and model identity.
    op.execute(APPEND_ONLY_FN.format(schema="ml"))
    op.execute(APPEND_ONLY_FN.format(schema="tracking"))
    op.execute(MODEL_IDENTITY_FN)
    for schema, table, events, fn in TRIGGERS:
        op.execute(
            f"CREATE TRIGGER {table}_{fn} BEFORE {events} ON {schema}.{table} "
            f"FOR EACH ROW EXECUTE FUNCTION {'ml' if fn == 'protect_model_identity' else schema}.{fn}()"
        )


def downgrade() -> None:
    for schema, table, _, fn in TRIGGERS:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_{fn} ON {schema}.{table}")
    op.execute("DROP FUNCTION IF EXISTS ml.protect_model_identity()")
    op.execute("DROP FUNCTION IF EXISTS ml.forbid_modification()")
    op.execute("DROP FUNCTION IF EXISTS tracking.forbid_modification()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_forecast_evaluations_forecast_id'), table_name='forecast_evaluations', schema='ml')
    op.drop_index(op.f('ix_ml_forecast_evaluations_evaluated_at'), table_name='forecast_evaluations', schema='ml')
    op.drop_index('ix_forecast_evaluations_model_horizon', table_name='forecast_evaluations', schema='ml')
    op.drop_index('ix_forecast_evaluations_iceberg', table_name='forecast_evaluations', schema='ml')
    op.drop_table('forecast_evaluations', schema='ml')
    op.drop_index(op.f('ix_ml_forecasts_generated_at'), table_name='forecasts', schema='ml')
    op.drop_index(op.f('ix_ml_forecasts_forecast_date'), table_name='forecasts', schema='ml')
    op.drop_index('ix_forecasts_model_horizon', table_name='forecasts', schema='ml')
    op.drop_index('ix_forecasts_iceberg_forecast_date', table_name='forecasts', schema='ml')
    op.drop_index('ix_forecasts_geom', table_name='forecasts', schema='ml', postgresql_using='gist')
    op.drop_table('forecasts', schema='ml')
    op.drop_index(op.f('ix_tracking_observation_revisions_observation_id'), table_name='observation_revisions', schema='tracking')
    op.drop_table('observation_revisions', schema='tracking')
    op.drop_index(op.f('ix_ml_forecast_sets_model_version'), table_name='forecast_sets', schema='ml')
    op.drop_index(op.f('ix_ml_forecast_sets_forecast_run_id'), table_name='forecast_sets', schema='ml')
    op.drop_index('ix_forecast_sets_iceberg_generated', table_name='forecast_sets', schema='ml')
    op.drop_table('forecast_sets', schema='ml')
    op.drop_index(op.f('ix_tracking_observations_provenance'), table_name='observations', schema='tracking')
    op.drop_index(op.f('ix_tracking_observations_ingestion_run_id'), table_name='observations', schema='tracking')
    op.drop_index('ix_observations_official_date', table_name='observations', schema='tracking', postgresql_where="provenance = 'official_usnic'")
    op.drop_index('ix_observations_iceberg_date_desc', table_name='observations', schema='tracking')
    op.drop_index('ix_observations_geom', table_name='observations', schema='tracking', postgresql_using='gist')
    op.drop_table('observations', schema='tracking')
    op.drop_index(op.f('ix_ml_model_status_events_model_version'), table_name='model_status_events', schema='ml')
    op.drop_table('model_status_events', schema='ml')
    op.drop_index('ix_model_metrics_lookup', table_name='model_metrics', schema='ml')
    op.drop_table('model_metrics', schema='ml')
    op.drop_index(op.f('ix_ml_forecast_runs_model_version'), table_name='forecast_runs', schema='ml')
    op.drop_table('forecast_runs', schema='ml')
    op.drop_index(op.f('ix_tracking_ingestion_row_errors_ingestion_run_id'), table_name='ingestion_row_errors', schema='tracking')
    op.drop_table('ingestion_row_errors', schema='tracking')
    op.drop_index(op.f('ix_tracking_icebergs_status'), table_name='icebergs', schema='tracking')
    op.drop_table('icebergs', schema='tracking')
    op.drop_index('uq_model_versions_single_deployed', table_name='model_versions', schema='ml', postgresql_where=sa.text("status = 'deployed'"))
    op.drop_index(op.f('ix_ml_model_versions_status'), table_name='model_versions', schema='ml')
    op.drop_index(op.f('ix_ml_model_versions_parent_version'), table_name='model_versions', schema='ml')
    op.drop_table('model_versions', schema='ml')
    op.drop_index(op.f('ix_tracking_ingestion_runs_checksum_sha256'), table_name='ingestion_runs', schema='tracking')
    op.drop_index('ix_ingestion_runs_source_fetched_at', table_name='ingestion_runs', schema='tracking')
    op.drop_table('ingestion_runs', schema='tracking')
    op.drop_index(op.f('ix_ml_retraining_runs_status'), table_name='retraining_runs', schema='ml')
    op.drop_table('retraining_runs', schema='ml')
    # ### end Alembic commands ###
