from __future__ import annotations

from datetime import date, datetime
from typing import Any, Literal

from pydantic import Field

from app.schemas.common import ApiModel, Provenance


class ForecastPoint(ApiModel):
    forecast_id: int
    horizon_days: int = Field(ge=1, le=7)
    forecast_date: date
    predicted_latitude: float
    predicted_longitude: float
    predicted_x_m: float = Field(description="EPSG:3031 metres")
    predicted_y_m: float = Field(description="EPSG:3031 metres")
    risk_radius_km_p90: float | None = Field(None, description="Empirical 90th-percentile error for this horizon")
    provenance: Literal["predicted"] = "predicted"


class InputEntry(ApiModel):
    observation_id: int | None
    date: date
    latitude: float
    longitude: float
    provenance: Provenance
    elapsed_days: float


class AnchorObservation(ApiModel):
    observation_id: int
    observation_date: date
    latitude: float
    longitude: float
    provenance: Provenance


class ForecastSetOut(ApiModel):
    forecast_set_id: int
    iceberg_id: str
    model_version: str
    is_champion: bool = Field(description="Generated by the currently deployed model")
    generated_at: datetime
    latest_observation_date: date
    requested_horizon: int
    is_stale: bool = Field(description="Anchor observation older than the staleness threshold")
    adapter_strategy: str
    diagnostics: dict[str, Any]
    anchor: AnchorObservation
    points: list[ForecastPoint]
    input_entries: list[InputEntry] | None = None


class ForecastRow(ApiModel):
    forecast_id: int
    forecast_set_id: int
    iceberg_id: str
    model_version: str
    generated_at: datetime
    latest_observation_date: date
    horizon_days: int
    forecast_date: date
    predicted_latitude: float
    predicted_longitude: float
    risk_radius_km_p90: float | None
    provenance: Literal["predicted"] = "predicted"


class MetricOut(ApiModel):
    protocol: str
    horizon_days: int | None
    n: int
    mae_km: float | None
    rmse_km: float | None
    median_km: float | None
    p90_km: float | None
    source: str
    computed_at: datetime


class StatusEventOut(ApiModel):
    from_status: str | None
    to_status: str
    reason: str
    actor: str
    created_at: datetime


class ModelVersionOut(ApiModel):
    version: str
    version_number: int
    parent_version: str | None
    architecture: str
    architecture_version: str
    input_sequence_length: int
    input_semantics: str
    forecast_horizon_days: int
    feature_names: list[str]
    adapter_strategy: str | None
    artifact_origin: str
    artifact_sha256: dict[str, str]
    training_data_cutoff: datetime | None
    training_started_at: datetime | None
    training_completed_at: datetime | None
    training_sample_count: int | None
    day1_error: float | None = Field(None, description="Mean error (km) at D+1 on the version's primary protocol")
    day3_error: float | None
    day7_error: float | None
    status: str
    status_reason: str | None
    deployed_at: datetime | None
    created_at: datetime


class ModelVersionDetail(ModelVersionOut):
    metrics: list[MetricOut]
    status_history: list[StatusEventOut]
    children: list[str]
    dataset_manifest: dict[str, Any] | None
    training_config: dict[str, Any] | None
    test_metrics: dict[str, Any] | None


class LineageNode(ApiModel):
    version: str
    parent_version: str | None
    status: str
    status_reason: str | None
    day7_error: float | None
    created_at: datetime


class HorizonMetrics(ApiModel):
    horizon_days: int
    n: int
    mae_km: float | None
    rmse_km: float | None
    median_km: float | None
    p90_km: float | None


class EvaluationOut(ApiModel):
    evaluation_id: int
    forecast_id: int
    iceberg_id: str
    model_version: str
    horizon_days: int
    forecast_date: date
    predicted_latitude: float
    predicted_longitude: float
    actual_latitude: float
    actual_longitude: float
    error_km: float
    actual_source: Provenance
    actual_observation_id: int
    actual_observation_date: date
    evaluated_at: datetime


class EvaluationSummary(ApiModel):
    model_version: str | None
    total: int
    by_horizon: list[HorizonMetrics]
    recent: list[EvaluationOut]
